preguntas(color_pelo,[]).
preguntas(vive,[]).
preguntas(hijos,[]).
preguntas(graduado,[]).
preguntas(edad,[]).
pregutnas(estatura,[]).
preguntas(deporte,[]).
preguntas(pelo,[]).
pregunta(relacion,[]).
pregunta(profesion,[]).
pregunta(genero,[]).
preguntas(representacion,[]).

oraciones(despedida,[]).
oraciones(bienvenida,[]).
oraciones(fallar,[]).
oraciones(adivinar,[]).
oraciones(acerto,[]).
oraciones(incompresion,[]).
oraciones(miestado,[]).
oraciones(aleatorias,[]).
oracio
